using Microsoft.AspNetCore.Components;
using OutWit.Common.MVVM.Blazor.ViewModels;
using OutWit.Web.Framework.Configuration;
using OutWit.Web.Framework.Services;

namespace OutWit.Web.Framework.ViewModels.Content;

public class SeoHeadViewModel : ViewModelBase
{
    #region Fields

    private string? m_socialImage;
    private string? m_twitterHandle;
    private string? m_resolvedCanonicalUrl;
    private string? m_siteName;
    private string? m_baseUrl;
    private string? m_logoUrl;

    #endregion

    #region Initialization

    protected override async Task OnInitializedAsync()
    {
        var config = await ConfigService.GetConfigAsync();
        m_twitterHandle = config.Seo.TwitterHandle;
        m_siteName = config.SiteName;
        m_baseUrl = config.BaseUrl.TrimEnd('/');

        // Use dark logo for og:logo (better visibility on light backgrounds in social media)
        if (!string.IsNullOrEmpty(config.LogoDark))
        {
            m_logoUrl = config.LogoDark.StartsWith("http") 
                ? config.LogoDark 
                : $"{m_baseUrl}{config.LogoDark}";
        }

        // Build canonical URL from current navigation if not provided.
        // Use a trailing slash so canonical matches the final 200 URL served by the
        // static host (it 308-redirects the non-slash form), keeping the
        // canonical/sitemap/redirect signals consistent.
        if (string.IsNullOrEmpty(CanonicalUrl))
        {
            var currentUri = new Uri(NavigationManager.Uri);
            var path = currentUri.AbsolutePath;
            if (!path.EndsWith("/"))
                path += "/";
            m_resolvedCanonicalUrl = $"{m_baseUrl}{path}";
        }
        else
        {
            m_resolvedCanonicalUrl = CanonicalUrl;
        }

        // Resolve social image: explicit > auto-generated > default
        m_socialImage = ResolveSocialImage(config);

        if (!string.IsNullOrEmpty(m_socialImage) && !m_socialImage.StartsWith("http"))
        {
            m_socialImage = $"{m_baseUrl}{m_socialImage}";
        }
    }

    /// <summary>
    /// Resolve the social image URL based on current page.
    /// Priority: 1) Explicit SocialImage parameter, 2) Auto-generated OG image, 3) Default from config
    /// </summary>
    private string? ResolveSocialImage(SiteConfig config)
    {
        // 1. If explicit SocialImage is provided, use it
        if (!string.IsNullOrEmpty(SocialImage))
            return SocialImage;

        // 2. Try to auto-detect OG image based on current URL
        var autoImage = GetAutoGeneratedOgImagePath();
        if (!string.IsNullOrEmpty(autoImage))
            return autoImage;

        // 3. Fall back to default from config
        return config.Seo.DefaultImage;
    }

    /// <summary>
    /// Generate OG image path based on current URL.
    /// Maps URL patterns to generated image filenames:
    /// - /blog/{slug} -> /og-images/blog-{slug}.png
    /// - /project/{slug} -> /og-images/project-{slug}.png
    /// - /article/{slug} -> /og-images/article-{slug}.png
    /// - /docs/{slug} -> /og-images/docs-{slug}.png
    /// - / (homepage) -> /og-images/default.png
    /// </summary>
    private string? GetAutoGeneratedOgImagePath()
    {
        var currentUri = new Uri(NavigationManager.Uri);
        var path = currentUri.AbsolutePath.TrimEnd('/');
        
        // Homepage
        if (string.IsNullOrEmpty(path) || path == "/")
            return "/og-images/default.png";

        var segments = path.Split('/', StringSplitOptions.RemoveEmptyEntries);
        
        if (segments.Length < 2)
            return null;

        var contentType = segments[0].ToLowerInvariant();
        var slug = segments[1];

        // Map content types to OG image prefixes
        var prefix = contentType switch
        {
            "blog" => "blog",
            "project" => "project",
            "article" => "article",
            "docs" => "docs",
            _ => null
        };

        if (prefix == null)
            return null;

        return $"/og-images/{prefix}-{slug}.png";
    }

    #endregion

    #region Properties

    protected string? ResolvedSocialImage => m_socialImage;
    
    protected string? TwitterHandle => m_twitterHandle;
    
    protected string? ResolvedCanonicalUrl => m_resolvedCanonicalUrl;
    
    protected string? SiteName => m_siteName;
    
    protected string? BaseUrl => m_baseUrl;
    
    /// <summary>
    /// Logo URL for og:logo meta tag.
    /// Uses dark logo for better visibility on light backgrounds.
    /// </summary>
    protected string? LogoUrl => m_logoUrl;
    
    /// <summary>
    /// RSS feed URL for the site.
    /// </summary>
    protected string? RssFeedUrl => m_baseUrl != null ? $"{m_baseUrl}/feed.xml" : null;
    
    /// <summary>
    /// Generate JSON-LD structured data for articles.
    /// </summary>
    protected string? JsonLdScript
    {
        get
        {
            if (OgType != "article")
                return null;

            var authorName = !string.IsNullOrEmpty(Author) ? Author : m_siteName ?? "Unknown";
            var datePublished = PublishDate?.ToString("yyyy-MM-dd") ?? DateTime.Now.ToString("yyyy-MM-dd");
            
            // Escape strings for JSON
            var escapedTitle = EscapeJsonString(Title);
            var escapedDescription = EscapeJsonString(Description);
            var escapedAuthor = EscapeJsonString(authorName);
            var escapedSiteName = EscapeJsonString(m_siteName ?? "");

            return $$"""
            {
              "@context": "https://schema.org",
              "@type": "Article",
              "headline": "{{escapedTitle}}",
              "description": "{{escapedDescription}}",
              "datePublished": "{{datePublished}}",
              "author": {
                "@type": "Person",
                "name": "{{escapedAuthor}}"
              },
              "publisher": {
                "@type": "Organization",
                "name": "{{escapedSiteName}}"
              },
              "mainEntityOfPage": {
                "@type": "WebPage",
                "@id": "{{EscapeJsonString(m_resolvedCanonicalUrl ?? "")}}"
              }
            }
            """;
        }
    }
    
    private static string EscapeJsonString(string value)
    {
        if (string.IsNullOrEmpty(value))
            return value;
        
        return value
            .Replace("\\", "\\\\")
            .Replace("\"", "\\\"")
            .Replace("\n", "\\n")
            .Replace("\r", "\\r")
            .Replace("\t", "\\t")
            // Escape '<' so a value containing "</script>" cannot break out of the
            // <script type="application/ld+json"> block. < is valid JSON.
            .Replace("<", "\\u003c");
    }

    #endregion

    #region Parameters

    [Parameter]
    public string Title { get; set; } = string.Empty;

    [Parameter]
    public string Description { get; set; } = string.Empty;

    [Parameter]
    public string? CanonicalUrl { get; set; }

    [Parameter]
    public string? SocialImage { get; set; }

    [Parameter]
    public string OgType { get; set; } = "website";

    [Parameter]
    public bool NoIndex { get; set; }

    [Parameter]
    public List<string> Keywords { get; set; } = [];
    
    [Parameter]
    public string? Author { get; set; }
    
    [Parameter]
    public DateTime? PublishDate { get; set; }
    
    /// <summary>
    /// Include RSS feed link in head. Default is true.
    /// </summary>
    [Parameter]
    public bool IncludeRssFeed { get; set; } = true;

    #endregion

    #region Injected Dependencies

    [Inject]
    public ConfigService ConfigService { get; set; } = null!;
    
    [Inject]
    public NavigationManager NavigationManager { get; set; } = null!;

    #endregion
}
